---
# tasks file for pxeserver

- name: setting up PXE server to boot Ubuntu 16.04
  block:
  
  - name: Download netboot in tftp folder
    shell: wget -r -np -nH --cut-dirs=3 -R "index.html*" http://{{ apache_mirror_server }}/ubuntu/install/netboot/
    args:
      chdir: /var/lib/tftpboot/

  - name: Setting up boot option for PXE book
    template:
      src: pxelinux.cfg.j2
      dest: /var/lib/tftpboot/pxelinux.cfg/default
      owner: tftp
      group: tftp
      mode: 0777

  - name: Copy ks.cfg file to for installation
    template:
      src: ks.cfg.j2
      dest: /var/www/html/ks.cfg
      mode: 0655
      
  - name: Copy preseed file 
    template:
      src: local.seed.j2
      dest: /var/www/html/local.seed
      mode: 0655

  become: true
  become_user: root
  when: ansible_distribution == "Ubuntu"
